/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiScratchpadRouteImport } from './routes/api/scratchpad'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as FoldersIndexRouteImport } from './routes/folders/index'
import { Route as FoldersIdRouteImport } from './routes/folders/$id'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesIdRouteImport } from './routes/notes/$id'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCategoriesIndexRouteImport } from './routes/api/categories/index'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories/$id'
import { Route as ApiMeIndexRouteImport } from './routes/api/me/index'
import { Route as ApiMeDataRouteImport } from './routes/api/me/data'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes/$id'
import { Route as ApiSubtasksIdRouteImport } from './routes/api/subtasks/$id'
import { Route as ApiTasksIndexRouteImport } from './routes/api/tasks/index'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks/$id'
import { Route as ApiTasksIdSubtasksRouteImport } from './routes/api/tasks/$id.subtasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScratchpadRoute = ApiScratchpadRouteImport.update({
  id: '/api/scratchpad',
  path: '/api/scratchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIndexRoute = FoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIdRoute = FoldersIdRouteImport.update({
  id: '/folders/$id',
  path: '/folders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIndexRoute = ApiCategoriesIndexRouteImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/api/categories/$id',
  path: '/api/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeIndexRoute = ApiMeIndexRouteImport.update({
  id: '/api/me/',
  path: '/api/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDataRoute = ApiMeDataRouteImport.update({
  id: '/api/me/data',
  path: '/api/me/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/api/notes/$id',
  path: '/api/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtasksIdRoute = ApiSubtasksIdRouteImport.update({
  id: '/api/subtasks/$id',
  path: '/api/subtasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIndexRoute = ApiTasksIndexRouteImport.update({
  id: '/api/tasks/',
  path: '/api/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/api/tasks/$id',
  path: '/api/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdSubtasksRoute = ApiTasksIdSubtasksRouteImport.update({
  id: '/subtasks',
  path: '/subtasks',
  getParentRoute: () => ApiTasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/scratchpad': typeof ApiScratchpadRoute
  '/api/search': typeof ApiSearchRoute
  '/folders/$id': typeof FoldersIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/folders/': typeof FoldersIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/me/data': typeof ApiMeDataRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/subtasks/$id': typeof ApiSubtasksIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/me/': typeof ApiMeIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/tasks/$id/subtasks': typeof ApiTasksIdSubtasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/scratchpad': typeof ApiScratchpadRoute
  '/api/search': typeof ApiSearchRoute
  '/folders/$id': typeof FoldersIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/folders': typeof FoldersIndexRoute
  '/notes': typeof NotesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/me/data': typeof ApiMeDataRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/subtasks/$id': typeof ApiSubtasksIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/me': typeof ApiMeIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/tasks/$id/subtasks': typeof ApiTasksIdSubtasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/scratchpad': typeof ApiScratchpadRoute
  '/api/search': typeof ApiSearchRoute
  '/folders/$id': typeof FoldersIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/folders/': typeof FoldersIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/me/data': typeof ApiMeDataRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/subtasks/$id': typeof ApiSubtasksIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/me/': typeof ApiMeIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/tasks/$id/subtasks': typeof ApiTasksIdSubtasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/api/scratchpad'
    | '/api/search'
    | '/folders/$id'
    | '/notes/$id'
    | '/tasks/$id'
    | '/folders/'
    | '/notes/'
    | '/tasks/'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/me/data'
    | '/api/notes/$id'
    | '/api/subtasks/$id'
    | '/api/tasks/$id'
    | '/api/categories/'
    | '/api/me/'
    | '/api/notes/'
    | '/api/tasks/'
    | '/api/tasks/$id/subtasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/api/scratchpad'
    | '/api/search'
    | '/folders/$id'
    | '/notes/$id'
    | '/tasks/$id'
    | '/folders'
    | '/notes'
    | '/tasks'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/me/data'
    | '/api/notes/$id'
    | '/api/subtasks/$id'
    | '/api/tasks/$id'
    | '/api/categories'
    | '/api/me'
    | '/api/notes'
    | '/api/tasks'
    | '/api/tasks/$id/subtasks'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/api/scratchpad'
    | '/api/search'
    | '/folders/$id'
    | '/notes/$id'
    | '/tasks/$id'
    | '/folders/'
    | '/notes/'
    | '/tasks/'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/me/data'
    | '/api/notes/$id'
    | '/api/subtasks/$id'
    | '/api/tasks/$id'
    | '/api/categories/'
    | '/api/me/'
    | '/api/notes/'
    | '/api/tasks/'
    | '/api/tasks/$id/subtasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ApiScratchpadRoute: typeof ApiScratchpadRoute
  ApiSearchRoute: typeof ApiSearchRoute
  FoldersIdRoute: typeof FoldersIdRoute
  NotesIdRoute: typeof NotesIdRoute
  TasksIdRoute: typeof TasksIdRoute
  FoldersIndexRoute: typeof FoldersIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
  ApiMeDataRoute: typeof ApiMeDataRoute
  ApiNotesIdRoute: typeof ApiNotesIdRoute
  ApiSubtasksIdRoute: typeof ApiSubtasksIdRoute
  ApiTasksIdRoute: typeof ApiTasksIdRouteWithChildren
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiMeIndexRoute: typeof ApiMeIndexRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiTasksIndexRoute: typeof ApiTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scratchpad': {
      id: '/api/scratchpad'
      path: '/api/scratchpad'
      fullPath: '/api/scratchpad'
      preLoaderRoute: typeof ApiScratchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders/'
      preLoaderRoute: typeof FoldersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$id': {
      id: '/folders/$id'
      path: '/folders/$id'
      fullPath: '/folders/$id'
      preLoaderRoute: typeof FoldersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories/'
      preLoaderRoute: typeof ApiCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/api/categories/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/': {
      id: '/api/me/'
      path: '/api/me'
      fullPath: '/api/me/'
      preLoaderRoute: typeof ApiMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/data': {
      id: '/api/me/data'
      path: '/api/me/data'
      fullPath: '/api/me/data'
      preLoaderRoute: typeof ApiMeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes/'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/api/notes/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtasks/$id': {
      id: '/api/subtasks/$id'
      path: '/api/subtasks/$id'
      fullPath: '/api/subtasks/$id'
      preLoaderRoute: typeof ApiSubtasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/': {
      id: '/api/tasks/'
      path: '/api/tasks'
      fullPath: '/api/tasks/'
      preLoaderRoute: typeof ApiTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/api/tasks/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id/subtasks': {
      id: '/api/tasks/$id/subtasks'
      path: '/subtasks'
      fullPath: '/api/tasks/$id/subtasks'
      preLoaderRoute: typeof ApiTasksIdSubtasksRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
  }
}

interface ApiTasksIdRouteChildren {
  ApiTasksIdSubtasksRoute: typeof ApiTasksIdSubtasksRoute
}

const ApiTasksIdRouteChildren: ApiTasksIdRouteChildren = {
  ApiTasksIdSubtasksRoute: ApiTasksIdSubtasksRoute,
}

const ApiTasksIdRouteWithChildren = ApiTasksIdRoute._addFileChildren(
  ApiTasksIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ApiScratchpadRoute: ApiScratchpadRoute,
  ApiSearchRoute: ApiSearchRoute,
  FoldersIdRoute: FoldersIdRoute,
  NotesIdRoute: NotesIdRoute,
  TasksIdRoute: TasksIdRoute,
  FoldersIndexRoute: FoldersIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
  ApiMeDataRoute: ApiMeDataRoute,
  ApiNotesIdRoute: ApiNotesIdRoute,
  ApiSubtasksIdRoute: ApiSubtasksIdRoute,
  ApiTasksIdRoute: ApiTasksIdRouteWithChildren,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiMeIndexRoute: ApiMeIndexRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiTasksIndexRoute: ApiTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
