/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiScratchpadRouteImport } from './routes/api/scratchpad'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as FoldersIndexRouteImport } from './routes/folders/index'
import { Route as FoldersIdRouteImport } from './routes/folders/$id'
import { Route as HabitsIndexRouteImport } from './routes/habits/index'
import { Route as HabitsIdRouteImport } from './routes/habits/$id'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesIdRouteImport } from './routes/notes/$id'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as ApiAiBreakdownRouteImport } from './routes/api/ai/breakdown'
import { Route as ApiAiExtractRouteImport } from './routes/api/ai/extract'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCategoriesIndexRouteImport } from './routes/api/categories/index'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories/$id'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as ApiHabitsIndexRouteImport } from './routes/api/habits/index'
import { Route as ApiHabitsIdRouteImport } from './routes/api/habits/$id'
import { Route as ApiMeIndexRouteImport } from './routes/api/me/index'
import { Route as ApiMeDataRouteImport } from './routes/api/me/data'
import { Route as ApiMeMergeRouteImport } from './routes/api/me/merge'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes/$id'
import { Route as ApiPushConfigRouteImport } from './routes/api/push/config'
import { Route as ApiPushSubscriptionRouteImport } from './routes/api/push/subscription'
import { Route as ApiPushTestRouteImport } from './routes/api/push/test'
import { Route as ApiSubtasksIdRouteImport } from './routes/api/subtasks/$id'
import { Route as ApiTasksIndexRouteImport } from './routes/api/tasks/index'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks/$id'
import { Route as ApiHabitsIdCheckinsRouteImport } from './routes/api/habits/$id.checkins'
import { Route as ApiTasksIdSkipRouteImport } from './routes/api/tasks/$id.skip'
import { Route as ApiTasksIdSnoozeRouteImport } from './routes/api/tasks/$id.snooze'
import { Route as ApiTasksIdSubtasksRouteImport } from './routes/api/tasks/$id.subtasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScratchpadRoute = ApiScratchpadRouteImport.update({
  id: '/api/scratchpad',
  path: '/api/scratchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIndexRoute = FoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIdRoute = FoldersIdRouteImport.update({
  id: '/folders/$id',
  path: '/folders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIdRoute = HabitsIdRouteImport.update({
  id: '/habits/$id',
  path: '/habits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiBreakdownRoute = ApiAiBreakdownRouteImport.update({
  id: '/api/ai/breakdown',
  path: '/api/ai/breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExtractRoute = ApiAiExtractRouteImport.update({
  id: '/api/ai/extract',
  path: '/api/ai/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIndexRoute = ApiCategoriesIndexRouteImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/api/categories/$id',
  path: '/api/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsIndexRoute = ApiHabitsIndexRouteImport.update({
  id: '/api/habits/',
  path: '/api/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsIdRoute = ApiHabitsIdRouteImport.update({
  id: '/api/habits/$id',
  path: '/api/habits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeIndexRoute = ApiMeIndexRouteImport.update({
  id: '/api/me/',
  path: '/api/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDataRoute = ApiMeDataRouteImport.update({
  id: '/api/me/data',
  path: '/api/me/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeMergeRoute = ApiMeMergeRouteImport.update({
  id: '/api/me/merge',
  path: '/api/me/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/api/notes/$id',
  path: '/api/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushConfigRoute = ApiPushConfigRouteImport.update({
  id: '/api/push/config',
  path: '/api/push/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscriptionRoute = ApiPushSubscriptionRouteImport.update({
  id: '/api/push/subscription',
  path: '/api/push/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/api/push/test',
  path: '/api/push/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtasksIdRoute = ApiSubtasksIdRouteImport.update({
  id: '/api/subtasks/$id',
  path: '/api/subtasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIndexRoute = ApiTasksIndexRouteImport.update({
  id: '/api/tasks/',
  path: '/api/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/api/tasks/$id',
  path: '/api/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsIdCheckinsRoute = ApiHabitsIdCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => ApiHabitsIdRoute,
} as any)
const ApiTasksIdSkipRoute = ApiTasksIdSkipRouteImport.update({
  id: '/skip',
  path: '/skip',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdSnoozeRoute = ApiTasksIdSnoozeRouteImport.update({
  id: '/snooze',
  path: '/snooze',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdSubtasksRoute = ApiTasksIdSubtasksRouteImport.update({
  id: '/subtasks',
  path: '/subtasks',
  getParentRoute: () => ApiTasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/api/scratchpad': typeof ApiScratchpadRoute
  '/api/search': typeof ApiSearchRoute
  '/folders/$id': typeof FoldersIdRoute
  '/habits/$id': typeof HabitsIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/folders/': typeof FoldersIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/ai/breakdown': typeof ApiAiBreakdownRoute
  '/api/ai/extract': typeof ApiAiExtractRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/habits/$id': typeof ApiHabitsIdRouteWithChildren
  '/api/me/data': typeof ApiMeDataRoute
  '/api/me/merge': typeof ApiMeMergeRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/subscription': typeof ApiPushSubscriptionRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/subtasks/$id': typeof ApiSubtasksIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/habits/': typeof ApiHabitsIndexRoute
  '/api/me/': typeof ApiMeIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/habits/$id/checkins': typeof ApiHabitsIdCheckinsRoute
  '/api/tasks/$id/skip': typeof ApiTasksIdSkipRoute
  '/api/tasks/$id/snooze': typeof ApiTasksIdSnoozeRoute
  '/api/tasks/$id/subtasks': typeof ApiTasksIdSubtasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/api/scratchpad': typeof ApiScratchpadRoute
  '/api/search': typeof ApiSearchRoute
  '/folders/$id': typeof FoldersIdRoute
  '/habits/$id': typeof HabitsIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/folders': typeof FoldersIndexRoute
  '/habits': typeof HabitsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/ai/breakdown': typeof ApiAiBreakdownRoute
  '/api/ai/extract': typeof ApiAiExtractRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/habits/$id': typeof ApiHabitsIdRouteWithChildren
  '/api/me/data': typeof ApiMeDataRoute
  '/api/me/merge': typeof ApiMeMergeRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/subscription': typeof ApiPushSubscriptionRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/subtasks/$id': typeof ApiSubtasksIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/habits': typeof ApiHabitsIndexRoute
  '/api/me': typeof ApiMeIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/habits/$id/checkins': typeof ApiHabitsIdCheckinsRoute
  '/api/tasks/$id/skip': typeof ApiTasksIdSkipRoute
  '/api/tasks/$id/snooze': typeof ApiTasksIdSnoozeRoute
  '/api/tasks/$id/subtasks': typeof ApiTasksIdSubtasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/api/scratchpad': typeof ApiScratchpadRoute
  '/api/search': typeof ApiSearchRoute
  '/folders/$id': typeof FoldersIdRoute
  '/habits/$id': typeof HabitsIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/folders/': typeof FoldersIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/ai/breakdown': typeof ApiAiBreakdownRoute
  '/api/ai/extract': typeof ApiAiExtractRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/habits/$id': typeof ApiHabitsIdRouteWithChildren
  '/api/me/data': typeof ApiMeDataRoute
  '/api/me/merge': typeof ApiMeMergeRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/subscription': typeof ApiPushSubscriptionRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/subtasks/$id': typeof ApiSubtasksIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/habits/': typeof ApiHabitsIndexRoute
  '/api/me/': typeof ApiMeIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/habits/$id/checkins': typeof ApiHabitsIdCheckinsRoute
  '/api/tasks/$id/skip': typeof ApiTasksIdSkipRoute
  '/api/tasks/$id/snooze': typeof ApiTasksIdSnoozeRoute
  '/api/tasks/$id/subtasks': typeof ApiTasksIdSubtasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/api/scratchpad'
    | '/api/search'
    | '/folders/$id'
    | '/habits/$id'
    | '/notes/$id'
    | '/tasks/$id'
    | '/folders/'
    | '/habits/'
    | '/notes/'
    | '/tasks/'
    | '/api/ai/breakdown'
    | '/api/ai/extract'
    | '/api/ai/status'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/cron/reminders'
    | '/api/habits/$id'
    | '/api/me/data'
    | '/api/me/merge'
    | '/api/notes/$id'
    | '/api/push/config'
    | '/api/push/subscription'
    | '/api/push/test'
    | '/api/subtasks/$id'
    | '/api/tasks/$id'
    | '/api/categories/'
    | '/api/habits/'
    | '/api/me/'
    | '/api/notes/'
    | '/api/tasks/'
    | '/api/habits/$id/checkins'
    | '/api/tasks/$id/skip'
    | '/api/tasks/$id/snooze'
    | '/api/tasks/$id/subtasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/api/scratchpad'
    | '/api/search'
    | '/folders/$id'
    | '/habits/$id'
    | '/notes/$id'
    | '/tasks/$id'
    | '/folders'
    | '/habits'
    | '/notes'
    | '/tasks'
    | '/api/ai/breakdown'
    | '/api/ai/extract'
    | '/api/ai/status'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/cron/reminders'
    | '/api/habits/$id'
    | '/api/me/data'
    | '/api/me/merge'
    | '/api/notes/$id'
    | '/api/push/config'
    | '/api/push/subscription'
    | '/api/push/test'
    | '/api/subtasks/$id'
    | '/api/tasks/$id'
    | '/api/categories'
    | '/api/habits'
    | '/api/me'
    | '/api/notes'
    | '/api/tasks'
    | '/api/habits/$id/checkins'
    | '/api/tasks/$id/skip'
    | '/api/tasks/$id/snooze'
    | '/api/tasks/$id/subtasks'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/api/scratchpad'
    | '/api/search'
    | '/folders/$id'
    | '/habits/$id'
    | '/notes/$id'
    | '/tasks/$id'
    | '/folders/'
    | '/habits/'
    | '/notes/'
    | '/tasks/'
    | '/api/ai/breakdown'
    | '/api/ai/extract'
    | '/api/ai/status'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/cron/reminders'
    | '/api/habits/$id'
    | '/api/me/data'
    | '/api/me/merge'
    | '/api/notes/$id'
    | '/api/push/config'
    | '/api/push/subscription'
    | '/api/push/test'
    | '/api/subtasks/$id'
    | '/api/tasks/$id'
    | '/api/categories/'
    | '/api/habits/'
    | '/api/me/'
    | '/api/notes/'
    | '/api/tasks/'
    | '/api/habits/$id/checkins'
    | '/api/tasks/$id/skip'
    | '/api/tasks/$id/snooze'
    | '/api/tasks/$id/subtasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  ApiScratchpadRoute: typeof ApiScratchpadRoute
  ApiSearchRoute: typeof ApiSearchRoute
  FoldersIdRoute: typeof FoldersIdRoute
  HabitsIdRoute: typeof HabitsIdRoute
  NotesIdRoute: typeof NotesIdRoute
  TasksIdRoute: typeof TasksIdRoute
  FoldersIndexRoute: typeof FoldersIndexRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiAiBreakdownRoute: typeof ApiAiBreakdownRoute
  ApiAiExtractRoute: typeof ApiAiExtractRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiHabitsIdRoute: typeof ApiHabitsIdRouteWithChildren
  ApiMeDataRoute: typeof ApiMeDataRoute
  ApiMeMergeRoute: typeof ApiMeMergeRoute
  ApiNotesIdRoute: typeof ApiNotesIdRoute
  ApiPushConfigRoute: typeof ApiPushConfigRoute
  ApiPushSubscriptionRoute: typeof ApiPushSubscriptionRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
  ApiSubtasksIdRoute: typeof ApiSubtasksIdRoute
  ApiTasksIdRoute: typeof ApiTasksIdRouteWithChildren
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiHabitsIndexRoute: typeof ApiHabitsIndexRoute
  ApiMeIndexRoute: typeof ApiMeIndexRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiTasksIndexRoute: typeof ApiTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scratchpad': {
      id: '/api/scratchpad'
      path: '/api/scratchpad'
      fullPath: '/api/scratchpad'
      preLoaderRoute: typeof ApiScratchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders/'
      preLoaderRoute: typeof FoldersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$id': {
      id: '/folders/$id'
      path: '/folders/$id'
      fullPath: '/folders/$id'
      preLoaderRoute: typeof FoldersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$id': {
      id: '/habits/$id'
      path: '/habits/$id'
      fullPath: '/habits/$id'
      preLoaderRoute: typeof HabitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/breakdown': {
      id: '/api/ai/breakdown'
      path: '/api/ai/breakdown'
      fullPath: '/api/ai/breakdown'
      preLoaderRoute: typeof ApiAiBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/extract': {
      id: '/api/ai/extract'
      path: '/api/ai/extract'
      fullPath: '/api/ai/extract'
      preLoaderRoute: typeof ApiAiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories/'
      preLoaderRoute: typeof ApiCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/api/categories/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits/': {
      id: '/api/habits/'
      path: '/api/habits'
      fullPath: '/api/habits/'
      preLoaderRoute: typeof ApiHabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits/$id': {
      id: '/api/habits/$id'
      path: '/api/habits/$id'
      fullPath: '/api/habits/$id'
      preLoaderRoute: typeof ApiHabitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/': {
      id: '/api/me/'
      path: '/api/me'
      fullPath: '/api/me/'
      preLoaderRoute: typeof ApiMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/data': {
      id: '/api/me/data'
      path: '/api/me/data'
      fullPath: '/api/me/data'
      preLoaderRoute: typeof ApiMeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/merge': {
      id: '/api/me/merge'
      path: '/api/me/merge'
      fullPath: '/api/me/merge'
      preLoaderRoute: typeof ApiMeMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes/'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/api/notes/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/config': {
      id: '/api/push/config'
      path: '/api/push/config'
      fullPath: '/api/push/config'
      preLoaderRoute: typeof ApiPushConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscription': {
      id: '/api/push/subscription'
      path: '/api/push/subscription'
      fullPath: '/api/push/subscription'
      preLoaderRoute: typeof ApiPushSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/test': {
      id: '/api/push/test'
      path: '/api/push/test'
      fullPath: '/api/push/test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtasks/$id': {
      id: '/api/subtasks/$id'
      path: '/api/subtasks/$id'
      fullPath: '/api/subtasks/$id'
      preLoaderRoute: typeof ApiSubtasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/': {
      id: '/api/tasks/'
      path: '/api/tasks'
      fullPath: '/api/tasks/'
      preLoaderRoute: typeof ApiTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/api/tasks/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits/$id/checkins': {
      id: '/api/habits/$id/checkins'
      path: '/checkins'
      fullPath: '/api/habits/$id/checkins'
      preLoaderRoute: typeof ApiHabitsIdCheckinsRouteImport
      parentRoute: typeof ApiHabitsIdRoute
    }
    '/api/tasks/$id/skip': {
      id: '/api/tasks/$id/skip'
      path: '/skip'
      fullPath: '/api/tasks/$id/skip'
      preLoaderRoute: typeof ApiTasksIdSkipRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/snooze': {
      id: '/api/tasks/$id/snooze'
      path: '/snooze'
      fullPath: '/api/tasks/$id/snooze'
      preLoaderRoute: typeof ApiTasksIdSnoozeRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/subtasks': {
      id: '/api/tasks/$id/subtasks'
      path: '/subtasks'
      fullPath: '/api/tasks/$id/subtasks'
      preLoaderRoute: typeof ApiTasksIdSubtasksRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
  }
}

interface ApiHabitsIdRouteChildren {
  ApiHabitsIdCheckinsRoute: typeof ApiHabitsIdCheckinsRoute
}

const ApiHabitsIdRouteChildren: ApiHabitsIdRouteChildren = {
  ApiHabitsIdCheckinsRoute: ApiHabitsIdCheckinsRoute,
}

const ApiHabitsIdRouteWithChildren = ApiHabitsIdRoute._addFileChildren(
  ApiHabitsIdRouteChildren,
)

interface ApiTasksIdRouteChildren {
  ApiTasksIdSkipRoute: typeof ApiTasksIdSkipRoute
  ApiTasksIdSnoozeRoute: typeof ApiTasksIdSnoozeRoute
  ApiTasksIdSubtasksRoute: typeof ApiTasksIdSubtasksRoute
}

const ApiTasksIdRouteChildren: ApiTasksIdRouteChildren = {
  ApiTasksIdSkipRoute: ApiTasksIdSkipRoute,
  ApiTasksIdSnoozeRoute: ApiTasksIdSnoozeRoute,
  ApiTasksIdSubtasksRoute: ApiTasksIdSubtasksRoute,
}

const ApiTasksIdRouteWithChildren = ApiTasksIdRoute._addFileChildren(
  ApiTasksIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  ApiScratchpadRoute: ApiScratchpadRoute,
  ApiSearchRoute: ApiSearchRoute,
  FoldersIdRoute: FoldersIdRoute,
  HabitsIdRoute: HabitsIdRoute,
  NotesIdRoute: NotesIdRoute,
  TasksIdRoute: TasksIdRoute,
  FoldersIndexRoute: FoldersIndexRoute,
  HabitsIndexRoute: HabitsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiAiBreakdownRoute: ApiAiBreakdownRoute,
  ApiAiExtractRoute: ApiAiExtractRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiHabitsIdRoute: ApiHabitsIdRouteWithChildren,
  ApiMeDataRoute: ApiMeDataRoute,
  ApiMeMergeRoute: ApiMeMergeRoute,
  ApiNotesIdRoute: ApiNotesIdRoute,
  ApiPushConfigRoute: ApiPushConfigRoute,
  ApiPushSubscriptionRoute: ApiPushSubscriptionRoute,
  ApiPushTestRoute: ApiPushTestRoute,
  ApiSubtasksIdRoute: ApiSubtasksIdRoute,
  ApiTasksIdRoute: ApiTasksIdRouteWithChildren,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiHabitsIndexRoute: ApiHabitsIndexRoute,
  ApiMeIndexRoute: ApiMeIndexRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiTasksIndexRoute: ApiTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
